version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - portfolio-network
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - portfolio-network
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@db:3306/portfolio
      - SECRET_KEY=your_secret_key_here
      - DEBUG=True

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/database.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=portfolio
    ports:
      - "3306:3306"
    networks:
      - portfolio-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

networks:
  portfolio-network:
    driver: bridge

volumes:
  mysql_data: